version: '3.1'

services:
  frontend:
    build:
      context: ./frontend
    image: tobalo1986/frontend:latest  

  backend:
    build:
      context: ./backend
    image: tobalo1986/backend:latest  
