
# Usa una imagen base de Node.js
FROM node:18

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo de dependencias e instálalas
COPY package*.json ./
RUN npm install

# Copia el resto de los archivos del backend
COPY . .

# Expone el puerto que usa el backend
EXPOSE 3001

# Comando para ejecutar el backend
CMD ["node", "app.js"]
